--- 
- hosts: localhost
  become: true
  tasks:
    - name: "loop through list"
      dnf:
        name: "{{ item }}"
        state: latest
      with_items:
        - docker
        - sl
        - python3
        - cowsay
